### ISSUE TITLE
combine with DNS repository

### ISSUE THREAD

**Issue by afeld** [18F/pages-redirects#149]
Seems like this repository has a lot of overlap with https://github.com/18F/dns, and that having the code for both in the same place would make our lives easier. Futhermore, it seems like we could more easily automate the [domain redirect](https://github.com/18F/pages-redirects#domain-redirects) steps.

@amirbey Thoughts?

**Comment by afeld** [comment]
https://github.com/18F/dns/pull/410#pullrequestreview-371285434

**Comment by amirbey** [comment]
@afeld - @davemcorwin and I are onboard with this idea. i have scheculed a meeting for us to discuss this further next week

**Comment by its-a-lisa-at-work** [comment]
Any outcome of this meeting to share here?

**Comment by afeld** [comment]
Can't remember if we took notes, but sounded like everyone was on board.

**Comment by its-a-lisa-at-work** [comment]
So should we close this issue and make another?

**Comment by afeld** [comment]
Removed the question mark 😉

**Comment by afeld** [comment]
Not a major pain point right now, so closing.
