### ISSUE TITLE
remove jobs.18f.gov and join.18f.gov

### ISSUE THREAD

**Issue by amirbey** [18F/pages-redirects#152]
Reference:
https://github.com/18F/dns/pull/410

**Comment by its-a-lisa-at-work** [comment]
@afeld or @JJediny  is this something that we're doing or that we're watching? If we're doing, could we move over to the TTS Tech Portfolio repo for better issue tracking?

**Comment by afeld** [comment]
Closed by https://github.com/18F/pages-redirects/pull/153.
