### ISSUE TITLE
reduce the steps

### ISSUE THREAD

**Issue by afeld** [18F/pages-redirects#155]
Right now, [adding a domain redirect](https://github.com/18F/pages-redirects#domain-redirects) requires:

1. Adding the domain in three places in this repository
1. Creating the CDN broker
1. Waiting for the broker to be created
1. Copying that URL into the DNS config

If #149 were done, I think we could have a Terraform module that does all these things in one fell swoop with a configuration in a single line/spot that sets up All The Things.

I was optimistic about the third-party module introduced in https://github.com/18F/dns/pull/410 for doing redirects entirely in AWS-managed services, but turns out [that approach is a bit limited](https://github.com/mediapop/terraform-aws-redirect/pull/3). I think sticking with nginx but making its configuration easier is preferable.

**Comment by davemcorwin** [comment]
With https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry, the best approach might be to combine the two repos and manage the whole thing with one terraform config...

**Comment by afeld** [comment]
Yep, exactly!

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
