### ISSUE TITLE
Add more pages migration instructions to README and/or to build script

### ISSUE THREAD

**Issue by jseppi** [18F/pages-redirects#33]
- Need to have the migrated `route` listed in `manifests/manifest-prod.yml`.
  - Actually we should have the build script automatically add the route.
- Need to setup a cdn-route and add DNS entry in 18f/dns.

cc @wslack 

Implementation sketch:
- Move `manifest-prod.yml` to `templates/`
- Modify `manifest-prod.yml` template to loop over a collection of `routes`
- Modify (and rename) `build-nginx-configs.js` to also create and output the `manifest-prod.yml` with all the routes

**Comment by wslack** [comment]
Wait, I'm confused. So now you'll add a redirect by adding a file to that collection?

**Comment by jseppi** [comment]
As currently implemented, redirects for pages.18f.gov/whatever -> whatever.18f.gov are handled by adding a new entry to the `pages.yml` file. However, going through this route/domain binding and cdn-route stuff has made me realize that the new page routes will also need to be listed in the manifest so that they are bound to the app. 

I am going to modify my implementation to automatically include the routes in the manifest so that users will still need to only have to modify `pages.yml`.

**Comment by wslack** [comment]
Ohhhh ok that's great!
