### ISSUE TITLE
Turn off reference to E/W Federalist

### ISSUE THREAD

**Issue by wslack** [18F/pages-redirects#88]
pages URLs should now all redirect. Anything that doesn't should get an error and request to ping federalist-support.

**Comment by jseppi** [comment]
To be clear: you want [this block](https://github.com/18F/pages-redirects/blob/master/templates/nginx.conf.njk#L59) to instead return an error page that says to go to email `federalist-support@gsa.gov`?

**Comment by wslack** [comment]
@jseppi yes, I think so. I'd welcome other ideas but I wouldn't want exception cases to just get a flat error page.

**Comment by jseppi** [comment]
Closed by https://github.com/18F/pages-redirects/pull/89
