### ISSUE TITLE
404 page is not returned on production site

### ISSUE THREAD

**Issue by jseppi** [18F/pages-redirects#90]
I thought I had properly taken care of showing a custom 404 message on requests for non-migrated 18F Pages (and anything else not specifically covered in the nginx config) in #89, but it doesn't seem to be working on production.

If you visit a non-existent path in your browser, like https://pages.18f.gov/boopadoop, you'll see a "302 Found" message:

<img width="464" alt="screen shot 2017-05-26 at 9 20 19 am" src="https://cloud.githubusercontent.com/assets/697848/26498399/8f0f18b6-41f4-11e7-9816-59f11acc37d1.png">

Here are some additional details from `curl`:

```sh
$ curl -Is https://pages.18f.gov/boopadoop
HTTP/1.1 404 Not Found
Content-Type: text/html
Content-Length: 154
Connection: keep-alive
Date: Fri, 26 May 2017 01:50:17 GMT
Location: https://guides.18f.gov/404.html
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 17c52a92-a96c-4363-788b-d41728ca0a1e
X-XSS-Protection: 1; mode=block
Age: 45038
X-Cache: Error from cloudfront
Via: 1.1 2e60888b24fa442131e50f158ca360a6.cloudfront.net (CloudFront)
X-Amz-Cf-Id: dEncFqIhI5EPtHb5VkwaebNaJFZnC7Q2HaSeMklXukfsf0kk6S4b2g==
```

It _looks_ like the request is being instead directed to guides.18f.gov, and requesting its `404.html` page, ~but I guess that 404 page looks like the 302 page in the above screenshot.~ Edited: most likely due to CloudFront error handling :\

To Do:
- [ ] update CloudFront distro for `pages.18f.gov` to have a 0 minimum TTL for error caching (must be done by cloud.gov operator)

**Comment by jseppi** [comment]
Pretty sure the problem is due to this line: [`rewrite ^/$ https://guides.18f.gov redirect;`](https://github.com/18F/pages-redirects/blob/master/templates/nginx.conf.njk#L52)

Tests also need to be amended. I thought I was properly testing the desired 404 behavior, but apparently not!

**Comment by jseppi** [comment]
Hrm, now I'm not so sure the line mentioned above is the problem. That line just matches the "bare" request to `https://pages.18f.gov` and redirects it to `https://guides.18f.gov`.

I'm now thinking it could be something to do with Cloud Front, which does some funky caching for error code responses, as described in the "Controlling How Long CloudFront Caches Errors" at http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages.html

**Comment by jseppi** [comment]
Adding to the CloudFront weirdness theory is that the response code is `404` and the guides page has a [custom 404.html](https://github.com/18F/guides/blob/18f-pages/404.html) page, yet still the default nginx 302 response page is shown.

**Comment by jseppi** [comment]
Added a To Do for setting a 0 minimal TTL for error caching. I'm not totally sure this will work, but that's my best working guess for solving the issue at this point.

**Comment by wslack** [comment]
@sheepeeh just passed along a report of this on Twitter; it looks like the 302 page is now firing for any site where the redirect has a case-matching issue - like https://pages.18f.gov/API-All-the-X/

**Comment by wslack** [comment]
So we can pursue the original issue, I think, or try to make the redirects not case sensitive. Thoughts?

**Comment by jseppi** [comment]
I think we should still try to get the CloudFront stuff fixed. I will see what it will take to make the `rewrite`s non-case-sensitive.

**Comment by jseppi** [comment]
I sent an email to cloud gov support today asking them to change the Error Minimum TTL for our CloudFront distro to 0.

**Comment by wslack** [comment]
Thanks to #93, @cpikas, @sheepeeh, and @jseppi - https://pages.18f.gov/API-All-the-X/ now redirects properly AND we made the error page work such that people have a support e-mail to send to! Yay!

**Comment by jseppi** [comment]
🎉 Thanks for the help all!
