### ISSUE TITLE
Users should be redirected to Federalist using via nginx-buildpack

### ISSUE THREAD

**Issue by jseppi** [18F/pages-redirects#99]
Same as https://github.com/18F/federalist-proxy/issues/31

This app currently uses the staticfiles-buildpack, but overrides the nginx.conf to meet the needs of our reverse proxy. Overriding the nginx.conf in the staticfiles-buildpack is now deprected by Cloud Foundry, and instead the nginx-buildpack should be used.

deprecation info: https://www.pivotaltracker.com/n/projects/1042066/stories/150296977

buildpack docs link: https://github.com/cloudfoundry/nginx-buildpack

**Comment by wslack** [comment]
I don't see how soon this will cause something to break but I'm not sure about that. Unclear on the level of effort to address though.

**Comment by amirbey** [comment]
User Story
A user should 1) be able to enter a federalist hosted domain/website into their browser and automatically  be able redirected to domain of their choosing 2) use their custom url to view their federalist built site using nginx-buildpack

Acceptance Criteria
- [ ] A user can be redirected to a domain (ie: 18f.gov to 18f.gsa.gov)
- [ ] A user can view their federalist built site using their custom domain (ie: https://federalist-docs.18f.gov/)

After evaluating, edit this part:

Level of effort - low

Implementation outline:
update manifest to use nginx-buildpack

**Comment by wslack** [comment]
Mind editing this into James's original post?
